name: Security Check on Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  dependencies-analysis:
    name: Dependencies Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Analyse avant PR (baseline)
      - name: Run OSV Scanner (Before)
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: --format=json > osv-before.json
          ref: ${{ github.event.pull_request.base.sha }}

      # Analyse courante
      - name: Run OSV Scanner (Current)
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: --format=json > osv-current.json

      # Analyse OSV avec sortie SARIF
      - name: Run OSV Analysis
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: --format=sarif > osv-results.sarif

      # Upload du rapport SARIF
      - name: Upload OSV SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif
          category: osv-scanner

  source-code-analysis:
    name: Source Code Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      security-events: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Analyse Semgrep
      - name: Run Semgrep Analysis
        run: |
          semgrep scan --sarif --config "p/java" \
            --baseline-commit ${{ github.event.pull_request.base.sha }} \
            > semgrep-results.sarif

      # Upload du rapport SARIF
      - name: Upload Semgrep SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep
